name: SonarQube Analysis

on:
  push:
    branches:
      - devan-baru

jobs:
  sonar-scan:
    runs-on: windows-latest

    steps:
      # Checkout kode Anda
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Sonar Scanner secara manual
      - name: Download and Install Sonar Scanner
        run: |
          Invoke-WebRequest -Uri https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-windows.zip -OutFile sonar-scanner.zip
          Expand-Archive -Path sonar-scanner.zip -DestinationPath .
          Rename-Item -Path ./sonar-scanner-cli-6.2.1.4610-windows -NewName sonar-scanner
          $env:PATH += ";$(Resolve-Path ./sonar-scanner/bin)"
          sonar-scanner.bat --version

      # Jalankan SonarQube Scanner
      - name: Run SonarQube Scanner
        run: sonar-scanner.bat -Dsonar.projectKey=web-commerce -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
