name: SonarQube Analysis

on:
  push:
    branches:
      - devan-baru

jobs:
  sonar-scan:
    runs-on: windows-latest

    steps:
      # Checkout kode Anda
      - name: Checkout code
        uses: actions/checkout@v3

      # Ekstrak sonar-scanner.zip yang ada di folder tools/
      - name: Extract sonar-scanner.zip
        run: |
          # Periksa apakah folder tools sudah ada
          if (-Not (Test-Path -Path "tools")) {
            New-Item -ItemType Directory -Path "tools"
          }
          
          # Ekstrak file sonar-scanner.zip ke folder tools/
          Expand-Archive -Path tools/sonar-scanner.zip -DestinationPath tools/ -Force
          
      # Menambahkan folder sonar-scanner ke dalam path
      - name: Set SONAR_SCANNER_HOME
        run: |
          $env:SONAR_SCANNER_HOME="C:\${{ github.workspace }}\tools\sonar-scanner-cli-6.2.1.4610-windows-x64"
          $env:PATH="$env:SONAR_SCANNER_HOME\bin;$env:PATH"
          echo "SONAR_SCANNER_HOME=$env:SONAR_SCANNER_HOME" >> $GITHUB_ENV
          echo "PATH=$env:PATH" >> $GITHUB_ENV

      # Jalankan SonarQube Scan
      - name: Run SonarQube Scan
        run: |
          sonar-scanner.bat
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
