name: SonarQube Analysis

on:
  push:
    branches:
      - devan-baru

jobs:
  sonar-scan:
    runs-on: windows-latest

    steps:
      # Checkout kode Anda
      - name: Checkout code
        uses: actions/checkout@v3

      # Jalankan SonarQube Scanner
      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # URL SonarQube Server
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token dari SonarQube
        run: |
          sonar-scanner
