name: SonarQube Analysis

on:
  push:
    branches:
      - devan-baru

jobs:
  sonar-scan:
    runs-on: ubuntu-latest # atau windows-latest jika ingin lingkungan Windows

    steps:
      # Checkout kode Anda
      - name: Checkout Code
        uses: actions/checkout@v3

      # Jalankan SonarQube Scanner
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.3
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
