name: SonarQube Analysis

on:
  push:
    branches:
      - devan-baru

jobs:
  sonar-scan:
    runs-on: windows-latest

    steps:
      # Checkout kode Anda
      - name: Checkout code
        uses: actions/checkout@v3

      # Jalankan SonarQube Scanner
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.1
        env:
          SONAR_HOST_URL:  ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
