name: SonarQube Analysis

on:
  push:
    branches:
      - devan-baru

jobs:
  sonar-scan:
    runs-on: windows-latest

    steps:
      # Checkout kode Anda
      - name: Checkout code
        uses: actions/checkout@v3

      # Tambahkan Sonar Scanner ke PATH
      - name: Add Sonar Scanner to PATH
        run: |
          $env:PATH += ";C:\sonar-scanner-6.2.1.4610-windows-x64\bin"
          echo $env:PATH

      # Jalankan Sonar Scanner
      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: 'http://localhost:9000' # URL SonarQube Server
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} # Token API SonarQube
        run: |
          sonar-scanner
